# Generated by Django 3.2.14 on 2022-08-02 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220802_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Home Appliances', 'Home Appliances')], null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
