# Generated by Django 4.0.6 on 2022-08-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_user_customer_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_searched', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Out of stock', 'Out of stock'), ('Not found', 'Not Found'), ('Pending', 'Pending')], max_length=250, null=True)),
            ],
        ),
    ]
